param(
  [string]$Root = "C:\Users\btf\AI-MemoryOS",
  [string]$CodexSkillRoot = (Join-Path $env:USERPROFILE ".codex\skills"),
  [string]$LegacyAgentSkillRoot = (Join-Path $env:USERPROFILE ".agents\skills")
)

$ErrorActionPreference = "Stop"

$activeSkills = @(
  "memory-curator",
  "routing-auditor",
  "bugfix-with-regression-test",
  "frontend-component-review"
)

$sourceRoot = Join-Path $Root "adapters\codex\skills"
if (-not (Test-Path -LiteralPath $sourceRoot)) {
  throw "MemoryOS Codex skill source directory not found: $sourceRoot"
}

if (-not (Test-Path -LiteralPath $CodexSkillRoot)) {
  New-Item -ItemType Directory -Path $CodexSkillRoot | Out-Null
}

function Test-MemoryOsSkillDestination {
  param(
    [string]$Path,
    [string]$SkillName
  )

  if (-not (Test-Path -LiteralPath $Path)) { return $true }

  $item = Get-Item -LiteralPath $Path -Force
  if ($item.LinkType -in @("Junction", "SymbolicLink")) { return $true }

  $skillFile = Join-Path $Path "SKILL.md"
  if (-not (Test-Path -LiteralPath $skillFile)) { return $false }

  $head = Get-Content -LiteralPath $skillFile -Encoding UTF8 -TotalCount 8
  return ($head -contains "name: $SkillName")
}

foreach ($skill in $activeSkills) {
  $source = Join-Path $sourceRoot $skill
  $dest = Join-Path $CodexSkillRoot $skill
  $sourceSkillFile = Join-Path $source "SKILL.md"

  if (-not (Test-Path -LiteralPath $sourceSkillFile)) {
    throw "Missing source skill file: $sourceSkillFile"
  }

  if (-not (Test-MemoryOsSkillDestination -Path $dest -SkillName $skill)) {
    throw "Destination exists but is not a MemoryOS-managed skill, skipped: $dest"
  }

  if (Test-Path -LiteralPath $dest) {
    Remove-Item -LiteralPath $dest -Recurse -Force
  }

  Copy-Item -LiteralPath $source -Destination $dest -Recurse -Force
  Set-Content -LiteralPath (Join-Path $dest ".memoryos-synced") -Encoding UTF8 -Value @(
    "source=$source",
    "synced_at=$(Get-Date -Format o)",
    "note=Generated by AI Memory OS sync. Edit the source directory, not this copy."
  )

  $legacyAgentPath = Join-Path $LegacyAgentSkillRoot $skill
  if (Test-Path -LiteralPath $legacyAgentPath) {
    $legacyItem = Get-Item -LiteralPath $legacyAgentPath -Force
    if ($legacyItem.LinkType -in @("Junction", "SymbolicLink")) {
      Remove-Item -LiteralPath $legacyAgentPath -Recurse -Force
    }
  }
}

Write-Host "Codex skills synced to: $CodexSkillRoot"
